### ISSUE TITLE
我刚刚测试了mvtec3d数据集下的bagel在RGB和Fusion2下的训练测试结果一模一样，可以帮我分析一下可能的原因吗谢谢

### ISSUE THREAD

**Issue by rock-lss** [TaoTao9/EasyNet#1]
不知道是不是预处理的原因

**Comment by TaoTao9** [comment]
你好可以请问其他类别也有这样子的情况吗，请问你的测试结果是怎么样的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TaoTao9/EasyNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 上午9:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[TaoTao9/EasyNet] 我刚刚测试了mvtec3d数据集下的bagel在RGB和Fusion2下的训练测试结果一模一样，可以帮我分析一下可能的原因吗谢谢 (Issue #1)





 
不知道是不是预处理的原因

**Comment by TaoTao9** [comment]
你好，因为我们提供的权重是Fusion1模式，如果使用Fusion2模式会导致不支持加载（只使用RGB分支），我们会修复这个问题以免引起歧义。

**Comment by TaoTao9** [comment]
你好可以请问其他类别也有这样子的情况吗，请问你的测试结果是怎么样的。
可能是我们提供的权重是Fusion1模式的，如果使用Fusion2模式会导致不正常加载，代码会只运行RGB分支，感谢你的反馈，我们会修复这个问题以免歧义！




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "TaoTao9/EasyNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 上午9:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[TaoTao9/EasyNet] 我刚刚测试了mvtec3d数据集下的bagel在RGB和Fusion2下的训练测试结果一模一样，可以帮我分析一下可能的原因吗谢谢 (Issue #1)





 
不知道是不是预处理的原因

**Comment by rock-lss** [comment]
但是在fusion1情况下我使用A100显卡会出现显存不够的问题

**Comment by rock-lss** [comment]
您这边有解决方案吗，我不知道为什么40g的显存不够哈哈哈。简单的说就是bagel在纯RGB和fusion2下面的测试结果一模一样。

**Comment by rock-lss** [comment]
AUC Image:  0.9741735537190083AP Image:  0.9937716594869666AUC Pixel:  0.7844440231096672AP Pixel:  0.033256266603588595aupro: 0.731035954166466
AUC Image:  0.9741735537190083AP Image:  0.9937716594869666AUC Pixel:  0.7844440231096672AP Pixel:  0.033256266603588595aupro: 0.731035954166466
结果是这样的

**Comment by rock-lss** [comment]
'bagel': 0.974, 'cable_gland': 1.0, 'carrot': 0.934, 
'cookie': 0.951, 'dowel': 0.916, 'foam': 0.934, 'peach' :0.896, 'potato': 0.716, 'rope': 0.992, 'tire': 0.804 平均值：0.912
这是纯RGB下的一组数据

**Comment by TaoTao9** [comment]
这个我暂时没有想到是什么原因，我这边重新安装和测试都没问题，且显存都是10G以内的占用，我这边机器是A6000，请问可以看一下你的运行命令行吗

**Comment by rock-lss** [comment]
nohup  python trainer.py --gpu_id 0 --obj_id 0 --layer_size 2layer --mode_type Fusion1 > bagel_Fusion1.txt 2>&1 &

**Comment by rock-lss** [comment]
这样会冲满40g的内存

**Comment by rock-lss** [comment]
然后我发现在fusion2下训练刚好够用

**Comment by rock-lss** [comment]
大概fusion2训练需要35GB的显存

**Comment by rock-lss** [comment]
![b8df89c32039175c1e7011388512149](https://github.com/TaoTao9/EasyNet/assets/151719972/4d244a93-245d-47a1-8233-bde814b0a3d0)这是我刚测得的一组数据，在fusion2下训练和测试的结果比纯RGB下低

**Comment by TaoTao9** [comment]
> ![b8df89c32039175c1e7011388512149](https://private-user-images.githubusercontent.com/151719972/300306763-4d244a93-245d-47a1-8233-bde814b0a3d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTMxODcsIm5iZiI6MTcwNjQ5Mjg4NywicGF0aCI6Ii8xNTE3MTk5NzIvMzAwMzA2NzYzLTRkMjQ0YTkzLTI0NWQtNDdhMS04MjMzLWJkZTgxNGIwYTNkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwMTQ4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGVkMjU3MWM5M2MwNmRjMTQwOTBmZmJjZDlkN2Y5YzA4NTcwMWRlNWFmZDcyYjUyNmY2NGZjOTZiZTc5ZmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._wy9w4oYhCMjjCgszwgvID6s-xynPTBVLBtoJ2ohwdM)这是我刚测得的一组数据，在fusion2下训练和测试的结果比纯RGB下低

请你仔细检查你的checkpoint.yaml文件的权重路径，测试结果请使用test.py文件，我们提供的是Fusion1的权重，使用Fusion2模式测试的结果肯定是不正确的。
