### ISSUE TITLE
在fusion2模式下训练，在fusion1模式下测试是可行的吗，我这样做好像数据更差了

### ISSUE THREAD

**Issue by rock-lss** [TaoTao9/EasyNet#2]

**Comment by TaoTao9** [comment]
请按照对应模式进行测试，Fusion1显存过大请适当调节batch大小，也即是'--bs'参数，可以设置小点以满足机器的显存。

**Comment by rock-lss** [comment]
好的，谢谢

**Comment by rock-lss** [comment]
![屏幕截图 2024-02-01 141804](https://github.com/TaoTao9/EasyNet/assets/151719972/772cc553-e90b-444d-9e79-b6ed9f34751b)
这是我重新在fusion1下训练测试后得到的数据，不知道为什么还是不如纯RGB下的

**Comment by TaoTao9** [comment]
> ![屏幕截图 2024-02-01 141804](https://private-user-images.githubusercontent.com/151719972/301405004-772cc553-e90b-444d-9e79-b6ed9f34751b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzQwNzMsIm5iZiI6MTcwNjc3Mzc3MywicGF0aCI6Ii8xNTE3MTk5NzIvMzAxNDA1MDA0LTc3MmNjNTUzLWU5MGItNDQ0ZC05ZTc5LWI2ZWQ5ZjM0NzUxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQwNzQ5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGUzNTIwYmE4MDFiMDg1Nzk2NDc0MGUwYzM2ZDc3ODZjN2Y4NWIxODViMzg0MDY4OGE0M2IyMmI4Yzk5YzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FDY3JDC3nLnWXpSLWB_W99cVtl28iyCQNqqQiAi7U94) 这是我重新在fusion1下训练测试后得到的数据，不知道为什么还是不如纯RGB下的

因为重建任务有多个损失收敛，训练过程波动比较大，训练到能收敛比较困难，我们在训练中也做了多次调节，重建任务缺失会比较难训练。

**Comment by TaoTao9** [comment]
请问你做的是3D AD这方面的研究工作吗

**Comment by TaoTao9** [comment]
这方面可以关注下https://github.com/M-3LAB/awesome-industrial-anomaly-detection的survey，目前这方面的工作M3DM和CPMF已经做到SOTA。

**Comment by TaoTao9** [comment]
这方面可以关注下https://github.com/M-3LAB/awesome-industrial-anomaly-detection的survey，目前这方面的工作M3DM和CPMF已经做到SOTA。

**Comment by rock-lss** [comment]
谢谢
